### ISSUE TITLE
Component - media - 400% CC takes up most of the video [RDI 2.28]

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/adapt-contrib-esdc-college-theme#14]
I tried viewing a video at 400% magnification (Reflow) and the navigation bar at the top is so large that I cannot see the entire video. If I want to see more of the video then part of the CC is being cut off.

**Comment by GGD4V** [comment]
Fixed. `.mejs-captions-text {
    padding: 3px 5px;
    background: url(background.png);
    background: rgba(20,20,20,0.5);
        background-image: none;
    white-space: pre-wrap;
    font-size: 2vw;
}`
